/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyInfo {
  'missionStatement' : string,
  'businessHours' : string,
  'capabilities' : string,
  'name' : string,
  'history' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface ContactInquiry {
  'id' : string,
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Industry {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface Product {
  'id' : string,
  'specifications' : string,
  'name' : string,
  'description' : string,
  'category' : ProductCategory,
  'applications' : string,
  'images' : Array<ExternalBlob>,
}
export type ProductCategory = { 'scrapShredders' : null } |
  { 'billetShearingMachines' : null } |
  { 'eotCranes' : null };
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addIndustry' : ActorMethod<[Industry], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getCompanyInfo' : ActorMethod<[], CompanyInfo>,
  'getIndustries' : ActorMethod<[], Array<Industry>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'removeProduct' : ActorMethod<[string], undefined>,
  'submitContactInquiry' : ActorMethod<[ContactInquiry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];