/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Industry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ProductCategory = IDL.Variant({
  'scrapShredders' : IDL.Null,
  'billetShearingMachines' : IDL.Null,
  'eotCranes' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'specifications' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : ProductCategory,
  'applications' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const Time = IDL.Int;
export const ContactInquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const CompanyInfo = IDL.Record({
  'missionStatement' : IDL.Text,
  'businessHours' : IDL.Text,
  'capabilities' : IDL.Text,
  'name' : IDL.Text,
  'history' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addIndustry' : IDL.Func([Industry], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
  'getIndustries' : IDL.Func([], [IDL.Vec(Industry)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'removeProduct' : IDL.Func([IDL.Text], [], []),
  'submitContactInquiry' : IDL.Func([ContactInquiry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Industry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ProductCategory = IDL.Variant({
    'scrapShredders' : IDL.Null,
    'billetShearingMachines' : IDL.Null,
    'eotCranes' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'specifications' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : ProductCategory,
    'applications' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Time = IDL.Int;
  const ContactInquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const CompanyInfo = IDL.Record({
    'missionStatement' : IDL.Text,
    'businessHours' : IDL.Text,
    'capabilities' : IDL.Text,
    'name' : IDL.Text,
    'history' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addIndustry' : IDL.Func([Industry], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
    'getIndustries' : IDL.Func([], [IDL.Vec(Industry)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'removeProduct' : IDL.Func([IDL.Text], [], []),
    'submitContactInquiry' : IDL.Func([ContactInquiry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };